version: '3.9'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/opt/app/api
    ports:
      - 8080:8080
    environment:
      API_ADDR: :8080
      DATABASE_URL: mongodb://root:secret@db:27017/temp?authSource=temp
    links:
      - db
  db:
    image: mongo:6.0.4
    logging:
      driver: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: temp
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
